###
GET http://localhost:3000 HTTP/1.1

### AUTH
POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
	"email":"nejcrogelsek40@gmail.com",
	"password": "Nejc123!",
	"profile_image": "undefined",
	"first_name": "Test",
	"last_name": "Uporabnik"
}

###
GET http://localhost:3000/auth/verify-email?token=d09e74cb636e209199ee6d6e92f9e826026df295ee36de370d19ac578a1b3a4568ede394706f97229d439aecc3240b19dac9cce150ea8c3c25aa00dc696df538 HTTP/1.1

###
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
	"email":"kwmwmsopooqongscdi@mrvpt.com",
	"password": "New123!"
}

### USERS
GET http://localhost:3000/users HTTP/1.1

###
GET http://localhost:3000/users/618d1c266c2cd45459c4ab5a HTTP/1.1

###
PATCH http://localhost:3000/users/61a8cde194f632666d0f37b2 HTTP/1.1
Content-Type: application/json

{
	"email": "nejcrogelsek80@gmail.com",
    "profile_image": "undefined.hihihihi",
    "first_name": "super",
    "last_name": "deluje"
}

###
DELETE http://localhost:3000/users/61a8da8359532bba38ba5c57 HTTP/1.1

### RESERVATIONS
GET http://localhost:3000/events/reservations HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt3bXdtc29wb29xb25nc2NkaUBtcnZwdC5jb20iLCJpZCI6IjYxOGQxYzI2NmMyY2Q0NTQ1OWM0YWI1YSIsImlhdCI6MTYzODIwNDI1NCwiZXhwIjoxNjM4MjA1MTU0fQ.pHjnSen-V5dfG0RNjT4eBNDfxA1Q0TDUJGMHtdJ0-Ug

###
GET http://localhost:3000/events/reservations/61913f8432d3b4b03c4b572a HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt3bXdtc29wb29xb25nc2NkaUBtcnZwdC5jb20iLCJpZCI6IjYxOGQxYzI2NmMyY2Q0NTQ1OWM0YWI1YSIsImlhdCI6MTYzNzE2ODczMywiZXhwIjoxNjM3MTY5NjMzfQ.d6ukBXuN9QA4EsHiouKXqcc5WA7SSXCSyY0p5mCbHq4

### EVENTS
GET http://localhost:3000/events HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt3bXdtc29wb29xb25nc2NkaUBtcnZwdC5jb20iLCJpZCI6IjYxOGQxYzI2NmMyY2Q0NTQ1OWM0YWI1YSIsImlhdCI6MTYzODI3OTgxMywiZXhwIjoxNjM4MjgwNzEzfQ.MKtjsdU4d7DYxQxb7XvZgebz5HUGTBX9_An9bwOdC8g

###
DELETE http://localhost:3000/events/61a62a1946ede7c9f5070090 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt3bXdtc29wb29xb25nc2NkaUBtcnZwdC5jb20iLCJpZCI6IjYxOGQxYzI2NmMyY2Q0NTQ1OWM0YWI1YSIsImlhdCI6MTYzODI3OTgxMywiZXhwIjoxNjM4MjgwNzEzfQ.MKtjsdU4d7DYxQxb7XvZgebz5HUGTBX9_An9bwOdC8g

###
GET http://localhost:3000/events/added-events HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5lamMucm9nZWxzZWs0MEBnbWFpbC5jb20iLCJpZCI6IjYxOGQxNzdiNTgzMWFkODVhNzFiMGUyOCIsImlhdCI6MTYzNjcxNzMyOCwiZXhwIjoxNjM2NzE4MjI4fQ.Jil5f5pI3cyJvkvTexZqlawjlE0j8a5toHfD9PaeN3s

###
POST http://localhost:3000/events HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt3bXdtc29wb29xb25nc2NkaUBtcnZwdC5jb20iLCJpZCI6IjYxOGQxYzI2NmMyY2Q0NTQ1OWM0YWI1YSIsImlhdCI6MTYzODAzNjc3MywiZXhwIjoxNjM4MDM3NjczfQ.gP0UO4TP7wvtp4xPClfMqg0PxRgndb_H5eufctYpn38

{
	"title": "Catch Santa Party",
	"description": "Santa will bring presents.",
	"location": "Under the tree",
	"event_image": "/event5.jpg",
	"max_visitors": 2,
	"user_id": "618d1c266c2cd45459c4ab5a",
	"date_start": "25.12.2021",
	"time_start": "23.59"
}

###
GET http://localhost:3000/events/4439843789e9fefe9 HTTP/1.1

### PRIVATE
GET http://localhost:3000/private/protected HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt3bXdtc29wb29xb25nc2NkaUBtcnZwdC5jb20iLCJpZCI6IjYxOGQxYzI2NmMyY2Q0NTQ1OWM0YWI1YSIsImlhdCI6MTYzNzI2NjY1OSwiZXhwIjoxNjM3MjY3NTU5fQ.s0jDlYU-_4Lehc0jgjAk0DEIEOo0ud-ex0Jg1lgigEE

### PUBLIC
GET http://localhost:3000/public/upload HTTP/1.1

###
GET http://localhost:3000/public/events HTTP/1.1

###
POST http://localhost:3000/public/events/search HTTP/1.1
Content-Type: application/json

{
	"search_term": "und",
	"date_term": "17.12.2021"
}

###
GET http://localhost:3000/public/events/url/gfdfhghgfjfhgjfh%3Fq=33726224-281d-4af1-b788-e98973dda587 HTTP/1.1

###
GET http://localhost:3000/public/events/upcoming HTTP/1.1

###
GET http://localhost:3000/public/events/recent HTTP/1.1

###
GET http://localhost:3000/public/events/61a62a1946ede7c9f5070090 HTTP/1.1

###
GET http://localhost:3000 HTTP/1.1