###
GET http://localhost:3000 HTTP/1.1

### PUBLIC
GET http://localhost:3000/public/events HTTP/1.1

### AUTH
POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
	"email":"nejcrogelsek0@gmail.com",
	"password": "Nejc123!",
	"profile_image": "undefined",
	"first_name": "Test",
	"last_name": "Uporabnik"
}

###
GET http://localhost:3000/auth/verify-email?token=aa113efc23e0689534c3bf0163dd3ca9833f62b6aef04aa1942f73209c7e0728b78cf9adc8de265145202f46b454d038cb633343a5fb9a492a9ff8f41a5b6b37 HTTP/1.1

###
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
	"email":"nejcrogelsek0@gmail.com",
	"password": "Nejc123!"
}

### USERS
GET http://localhost:3000/users HTTP/1.1

###
GET http://localhost:3000/users/618befee0658295b7ef2f407 HTTP/1.1

###
PATCH http://localhost:3000/users/618befee0658295b7ef2f407 HTTP/1.1
Content-Type: application/json

{
	"email":"nejcrogelsek0@gmail.com",
	"first_name": "Nejc",
	"last_name": "Rogelšek"
}

###
DELETE http://localhost:3000/users/618bf2e85c5850226c82c343 HTTP/1.1

### EVENTS
GET http://localhost:3000/events HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5lamNyb2dlbHNlazQwQGdtYWlsLmNvbSIsImlhdCI6MTYzNjU3ODEwMSwiZXhwIjoxNjM2NTc5MDAxfQ.0wXrM_clt9Fi-TvfuG88fVgeFaREKmm9LH-ynjTy6O4

###
GET http://localhost:3000/events/4439843789e9fefe9 HTTP/1.1

###
GET http://localhost:3000/public/events HTTP/1.1

###
GET http://localhost:3000/public/events/1 HTTP/1.1

###
GET http://localhost:3000/public/upload HTTP/1.1