###
GET http://localhost:8081 HTTP/1.1

###
GET http://localhost:8081/users HTTP/1.1

###
GET http://localhost:8081/users/1 HTTP/1.1

###
GET http://localhost:8081/todos HTTP/1.1
Content-Type: application/json
Authorization: Bearer token34534534534

###
POST http://localhost:8081/auth/register HTTP/1.1
Content-Type: application/json

{
	"email":"nejc@gmail.com",
	"password": "Nejc123!",
	"profile_image": "undefined",
	"first_name": "Nejc",
	"last_name": "Rogla",
	"email_token": "nekaj",
	"confirmed": false,
}

###
POST http://localhost:8081/auth/register HTTP/1.1
Content-Type: application/json

{
	"email":"nejc@gmail.com",
	"password": "Nejc123!"
}
